import random
homework_questions = [
    "Can you explain the difference between a weak and strong entity in ER-diagrams?",
    "How do you determine the primary key in an ER-diagram?",
    "What are the rules for converting an ER-diagram into a relational schema?",
    "Can you help me with an example of a one-to-many relationship?",
    "What is a composite key, and when should it be used?",
    "How do you normalize a database to the 3rd Normal Form (3NF)?",
    "What are the differences between 1NF, 2NF, and 3NF?",
    "Can you give an example of a transitive dependency?",
    "How do I remove partial dependencies from a relation?",
    "What is the difference between a candidate key and a superkey?",
    "How do I handle a many-to-many relationship in a relational database?",
    "Can you explain the difference between a foreign key and a primary key?",
    "What is a surrogate key, and when is it useful?",
    "How can I identify multivalued dependencies in a database schema?",
    "What are some common pitfalls in database normalization?",
    "How do I handle a recursive relationship in an ER-diagram?",
    "Can you explain the steps involved in converting an ER-diagram to a relational schema?",
    "How do I determine if a relation is in BCNF?",
    "What is the difference between BCNF and 3NF?",
    "Can you help me understand how to draw a ternary relationship in an ER-diagram?",
    "How do you model inheritance in an ER-diagram?",
    "Can you give an example of an entity with multiple attributes?",
    "How do I deal with overlapping entities in an ER-diagram?",
    "What are the guidelines for naming attributes in an ER-diagram?",
    "How do I represent an ISA relationship in an ER-diagram?",
    "Can you explain the concept of a derived attribute?",
    "How do I handle weak entities when normalizing a database?",
    "Can you walk me through the process of creating an ER-diagram from a problem statement?",
    "What is the purpose of a relational schema?",
    "How do I convert a multi-valued attribute into a relation?",
    "Can you explain the concept of referential integrity?",
    "What are the common types of relationships in an ER-diagram?",
    "How do I model a relationship between an entity and itself?",
    "What is the purpose of an ER-diagram in database design?",
    "Can you explain the concept of functional dependency?",
    "How do I know if my relational schema is properly normalized?",
    "What are the advantages of database normalization?",
    "How do I model an ER-diagram for a real-world problem?",
    "Can you explain the steps in the database design process?",
    "What is the difference between a relation and a table in a database?",
    "How do I model optional attributes in an ER-diagram?",
    "What is the difference between a total and partial participation in an ER-diagram?",
    "How do I identify functional dependencies in a set of attributes?",
    "Can you give an example of a relation that violates 2NF?",
    "How do I know if a relation has redundant data?",
    "What are the steps to normalize a database schema?",
    "Can you explain how to identify a primary key in a relation?",
    "How do I handle multi-valued attributes when designing a database?",
    "Can you help me with an example of a functional dependency that violates BCNF?",
    "Should foreign keys be marked in an ER-diagram?"
]

lab_questions = [
    "How do I connect a Python script to a MySQL database?",
    "What is the syntax for a basic SELECT statement in SQL?",
    "Can you explain how to perform a JOIN between two tables?",
    "How do I use GROUP BY in SQL to aggregate data?",
    "What is the difference between INNER JOIN and OUTER JOIN?",
    "How do I filter results using the WHERE clause in SQL?",
    "Can you explain how to use the COUNT() function in SQL?",
    "What is the purpose of the HAVING clause in SQL?",
    "How do I insert data into a table using SQL?",
    "Can you show me how to update records in a SQL database?",
    "How do I delete records from a table in SQL?",
    "What is the syntax for creating a table in SQL?",
    "How do I add a primary key to an existing table in SQL?",
    "Can you explain the difference between DELETE and TRUNCATE?",
    "How do I retrieve the top N rows in a SQL query?",
    "What is the purpose of the ORDER BY clause in SQL?",
    "How do I use the LIMIT clause in SQL?",
    "Can you show me how to use subqueries in SQL?",
    "What are the different types of SQL joins?",
    "How do I use the LIKE operator for pattern matching in SQL?",
    "How do I create an index on a table in SQL?",
    "Can you explain how to perform a self-join in SQL?",
    "What is the purpose of the DISTINCT keyword in SQL?",
    "How do I combine results from multiple tables using UNION?",
    "Can you show me how to use the CASE statement in SQL?",
    "How do I create a view in SQL?",
    "What is the difference between a view and a table in SQL?",
    "How do I optimize a SQL query for better performance?",
    "Can you explain how to use the EXISTS clause in SQL?",
    "How do I handle NULL values in SQL queries?",
    "What are aggregate functions in SQL?",
    "How do I perform a full-text search in a SQL database?",
    "Can you explain how to use window functions in SQL?",
    "What is the purpose of the COALESCE function in SQL?",
    "How do I create a stored procedure in SQL?",
    "Can you explain how to use triggers in SQL?",
    "How do I handle transactions in SQL?",
    "What is the difference between COMMIT and ROLLBACK?",
    "How do I manage database permissions using SQL?",
    "Can you show me how to use the REPLACE function in SQL?",
    "How do I copy data from one table to another in SQL?",
    "What are the best practices for writing SQL queries?",
    "How do I retrieve the schema of a table in SQL?",
    "Can you explain how to use the IN clause in SQL?",
    "How do I perform a left join between two tables in SQL?",
    "What is the difference between CHAR and VARCHAR in SQL?",
    "How do I use the CONCAT function in SQL?",
    "Can you explain how to implement pagination in a SQL query?",
    "How do I set up a foreign key constraint in SQL?",
    "Are we allowed to use limit?"
]

admin_questions = [
    "What is the deadline for submitting the final project?",
    "How do I register for the lab sessions?",
    "Can I request an extension for my homework submission?",
    "What are the prerequisites for this course?",
    "Is attendance mandatory for all lectures?",
    "How will the final grade be calculated?",
    "What is the grading scale for this course?",
    "Can I reschedule a lab session if I miss one?",
    "How do I access the course materials online?",
    "What are the office hours for the TAs?",
    "Will the lectures be recorded and made available online?",
    "How do I access the online database for the labs?",
    "What is the format of the final exam?",
    "How many homeworks will there be in total?",
    "Can I work in groups for the homework assignments?",
    "What is the penalty for late submissions?",
    "Are there any recommended textbooks for this course?",
    "How do I find out my grades for the assignments?",
    "Can I switch my lab group after the first week?",
    "What should I do if I encounter issues with the lab software?",
    "How do I submit my homework assignments?",
    "Are there any extra credit opportunities in this course?",
    "How do I contact the course coordinator?",
    "What should I do if I can't attend the final exam?",
    "Is there a discussion forum for this course?",
    "How do I get access to the course's online portal?",
    "Are there any prerequisites for the final project?",
    "What is the policy on plagiarism for this course?",
    "Can I get feedback on my homework before the submission?",
    "How do I apply for re-evaluation of an assignment?",
    "What should I do if I have a conflict with the exam schedule?",
    "How are the labs graded?",
    "Can I attend a different lab session than the one I'm registered for?",
    "What is the format of the lab reports?",
    "Are there any sample exams available for practice?",
    "Can I bring notes to the final exam?",
    "What resources are allowed during lab sessions?",
    "How do I get help with understanding the course material?",
    "Are there any study groups I can join?",
    "What is the policy on using external libraries in the labs?",
    "How do I report a bug in the lab environment?",
    "What is the weight of the final exam in the overall grade?",
    "Can I retake the final exam if I fail?",
    "Are there any tutorials available for the lab exercises?",
    "How do I sign up for a project topic?",
    "Will there be any guest lectures during the course?",
    "How do I appeal a grade I received?",
    "What should I do if I fall behind in the course?",
    "Are there any make-up assignments available?",
    "What is the procedure for dropping the course?",
]


questions = homework_questions + lab_questions + admin_questions
questions = list(dict.fromkeys(questions))
random.shuffle(questions)

training_set = questions[:125]
test_set = questions[125:]
