import random
sales_questions = [
    "What is the price of this car?",
    "Can I take this car for a test drive?",
    "What is the warranty coverage?",
    "What are the financing options available?",
    "Can you explain the different trim levels and options?",
    "What is my trade-in worth?",
    "How do you determine the trade-in value?",
    "What additional fees should I expect?",
    "How long does the purchase process take?",
    "Can I get a breakdown of the final cost?",
    "What are the fuel efficiency and maintenance costs?",
    "Does this car have the latest safety features?",
    "Can I see the vehicle's history report?",
    "What are the terms for leasing this vehicle?",
    "What happens at the end of the lease?",
    "What is included in the service and maintenance package?",
    "Can I return the car if I change my mind?",
    "What should I do if I have a problem with the car after purchase?",
    "What is the price of the car?",
    "Are there any current promotions or discounts?",
    "What is the warranty coverage on this vehicle?",
    "Can I take the car for a test drive?",
    "What is the fuel efficiency of this car?",
    "Are there any additional fees I should be aware of?",
    "What financing options are available?",
    "Can you provide a detailed breakdown of the monthly payments?",
    "Has the car been involved in any accidents?",
    "What is the car's service history?",
    "Can I see the vehicle's maintenance records?",
    "What safety features does this car have?",
    "Are there any recalls on this model?",
    "Can I trade in my current car?",
    "What is the trade-in value of my current car?",
    "Is the price negotiable?",
    "What is included in the price?",
    "Are there any add-ons or packages available?",
    "How long has this car been on the lot?",
    "What is the estimated delivery time for a new car order?",
    "What is the resale value of this car?",
    "Can you provide a vehicle history report?",
    "What are the insurance costs for this car?",
    "How often does this car need servicing?",
    "What is the cost of parts and maintenance for this model?",
    "Are there any special features or upgrades available?",
    "Can I customize the car before purchase?",
    "What is your return policy?",
    "Do you offer any service plans or extended warranties?",
    "Can I see the car's inspection report?",
    "Can you beat the guys across town on price?",
    "What is your commission on this deal?",
    "Can we amend the sales contract?",
    "Do I qualify for a lease?"
]
garage_questions = [
    "What is wrong with my car?",
    "How much will it cost to fix?",
    "How long will the repair take?",
    "Is it safe to drive my car?",
    "Can you explain the problem in detail?",
    "Do you have the necessary parts in stock?",
    "What caused the problem?",
    "Can you provide a written estimate?",
    "Are there any additional fees I should be aware of?",
    "Do you offer any warranties on parts and labor?",
    "What regular maintenance does my car need?",
    "When should I schedule my next service?",
    "Can you check for other potential issues?",
    "Are your mechanics certified?",
    "Do you use OEM (Original Equipment Manufacturer) parts?",
    "Can I see the damaged parts?",
    "What should I do if the problem recurs?",
    "How can I maintain my car to avoid future problems?",
    "What are the signs of a similar problem in the future?",
    "Do you offer towing services?",
    "Can you provide a loaner car or shuttle service?",
    "Do you have any customer reviews or references?",
    "What is causing the issue with my car?",
    "How much will the repair cost?",
    "How long will the repair take?",
    "Is it safe to drive my car in its current condition?",
    "What are the most urgent repairs needed?",
    "Can you provide a detailed estimate for the repairs?",
    "What are my options for fixing this problem?",
    "Are the parts you use new or refurbished?",
    "Can I see the damaged parts that were replaced?",
    "Is there a warranty on the repair work?",
    "What maintenance does my car need right now?",
    "How often should I get my car serviced?",
    "What brand of parts do you use?",
    "Can I bring my own parts for the repair?",
    "Is it cheaper to repair or replace the part?",
    "What are the signs that this issue might happen again?",
    "Can you explain the repair process?",
    "Do you have experience with my car's make and model?",
    "Can you check for other potential issues?",
    "What regular maintenance can prevent this problem in the future?",
    "Why is my check engine light on?",
    "Why is my car making a strange noise?",
    "Why is my car vibrating?",
    "Why is my car leaking fluid?",
    "Why is my car overheating?",
    "Why are my brakes squeaking?",
    "Why does my car have trouble starting?",
    "Why is my fuel efficiency low?",
    "How can I improve my car's performance?",
    "What are the recommended tire pressure levels?",
    "When should I replace my tires?",
    "How often should I change my oil?",
    "What type of oil should I use?",
    "When should I replace my car's battery?",
    "How can I prolong the life of my car battery?",
    "When should I replace my brake pads?",
    "What should I do if my car starts to overheat?",
    "Can you check my car's alignment?",
    "How often should I replace my air filter?",
    "Can I see the damaged parts that were replaced?"
]

questions = sales_questions + garage_questions
questions = list(dict.fromkeys(questions))
random.shuffle(questions)

training_set = questions[:100]
test_set = questions[100:]  # This is of size 10
